INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (0,607,7,925.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (0,1122,4,678.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (0,528,6,367.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (0,676,6,178.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (1,893,9,978.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (1,699,6,748.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,1031,9,674.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,33,5,285.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,184,7,223.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,1027,1,569.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,1144,7,980.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,43,9,39.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,56,9,478.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,346,9,596.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (2,200,5,949.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (3,1014,1,484.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (3,441,7,50.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (3,938,0,861.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (3,802,5,721.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,901,6,182.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,260,4,961.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,588,8,722.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,904,5,323.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,544,5,180.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,604,3,272.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,1059,6,870.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,489,0,794.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,416,1,930.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (4,852,9,11.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (5,909,9,645.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (5,231,2,366.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,662,8,360.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,119,3,144.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,107,8,437.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,1137,4,176.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,172,8,300.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,35,0,142.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,63,0,754.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,343,7,681.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (6,440,0,962.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,18,9,749.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,836,3,782.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,1092,6,134.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,987,3,336.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,1100,7,385.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,390,7,152.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,578,3,614.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,1032,6,840.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (7,264,7,958.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,941,2,226.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,966,9,770.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,1040,9,355.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,214,0,606.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,456,6,760.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,1107,5,40.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (8,684,9,516.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (9,90,7,809.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (9,404,6,62.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (10,1129,7,878.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (10,504,1,372.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (10,965,6,258.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (10,183,8,186.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (10,843,5,257.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (10,1012,7,159.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,384,7,261.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,239,1,756.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,254,0,518.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,962,7,387.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,473,6,160.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,1108,6,945.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (11,842,0,807.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (12,77,7,736.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (12,847,7,295.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (12,927,1,790.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,922,1,284.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,745,6,70.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,1051,6,339.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,783,0,875.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,414,6,330.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,15,7,544.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,462,9,453.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (13,484,7,264.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,1069,1,923.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,1046,5,290.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,240,7,861.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,185,2,585.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,360,1,72.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,865,5,880.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (14,1119,8,506.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,328,3,891.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,232,5,19.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,1040,9,922.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,1127,2,583.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,1120,8,881.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,551,0,30.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (15,228,6,914.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,799,1,135.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,837,5,943.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,420,0,743.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,674,6,75.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,646,4,839.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,1124,6,897.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (16,203,5,14.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (17,849,0,101.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (17,423,7,210.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (17,667,9,271.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (17,112,2,137.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (17,1071,1,187.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (18,390,5,430.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (18,1104,3,249.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (18,774,2,766.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (18,662,2,971.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (18,1116,1,349.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (18,200,7,293.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,617,7,76.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,871,3,464.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,679,3,518.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,569,1,791.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,583,0,819.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,504,1,145.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,552,2,931.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,436,8,223.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,254,6,133.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (19,429,7,459.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (20,1019,8,115.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (20,157,4,268.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (20,781,5,341.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (20,928,2,723.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (20,342,6,61.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (20,190,0,20.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (21,66,2,364.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (21,296,3,261.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (21,468,3,886.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (21,359,9,78.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (22,190,5,568.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (22,126,8,68.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (22,463,1,634.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (22,767,9,471.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (22,326,3,244.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (22,411,8,214.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,823,2,988.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,963,4,925.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,511,4,999.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,356,1,42.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,1023,7,758.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,886,3,22.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (23,379,6,224.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,487,5,512.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,852,0,17.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,506,8,776.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,317,3,35.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,685,5,516.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,1080,9,965.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,625,1,714.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,306,2,998.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,814,6,28.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (24,1126,9,558.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (25,834,1,239.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (25,1143,0,428.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (25,1108,9,697.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (25,175,0,843.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (25,463,6,791.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (26,32,6,66.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (26,557,7,460.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (27,289,1,581.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (27,938,0,229.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (28,647,9,487.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (28,45,6,924.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (29,652,1,213.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (29,304,4,519.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (29,373,7,96.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (29,589,7,718.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (29,1109,3,567.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,563,9,468.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,788,9,525.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,429,6,908.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,336,4,827.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,921,5,110.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,924,8,0.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,1004,3,181.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,671,9,503.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (30,66,9,730.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (31,451,2,424.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (31,609,9,905.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (31,835,2,837.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (31,1126,2,238.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,354,8,58.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,44,2,859.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,758,0,523.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,832,2,626.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,178,2,154.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,272,3,835.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (32,526,0,316.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,337,2,454.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,866,8,585.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,665,3,872.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,562,9,954.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,725,8,853.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,103,8,512.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,24,6,81.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,542,3,400.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,909,0,240.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (33,430,5,527.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (34,1114,1,338.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (34,15,2,113.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (34,65,5,227.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (34,859,4,902.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (34,617,8,325.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (34,778,9,183.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,886,2,576.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,284,1,350.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,132,2,293.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,811,7,238.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,54,2,985.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,657,8,816.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,1091,1,635.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,380,3,311.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,57,3,916.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (35,962,1,120.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,412,1,644.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,1129,8,916.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,96,7,73.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,769,1,255.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,840,0,564.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,177,7,721.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (36,273,2,14.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (37,172,9,188.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (37,703,1,588.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (37,540,4,75.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (37,764,7,961.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (38,225,0,504.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (38,382,7,658.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (39,290,1,819.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (39,203,6,261.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (39,443,4,12.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (39,344,9,337.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (39,372,1,764.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (40,856,7,113.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (40,1054,5,991.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (40,3,9,175.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (40,776,4,59.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (40,688,2,905.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (40,1138,5,697.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,379,9,68.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,962,4,291.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,882,6,565.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,338,2,207.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,411,5,789.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,1087,1,329.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,882,0,802.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (41,159,8,523.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (42,585,0,816.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (42,749,2,541.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (42,46,1,776.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (42,1036,8,113.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,287,7,215.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,943,6,986.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,669,1,352.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,412,1,54.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,1050,1,499.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,15,3,919.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (43,777,2,780.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,103,2,873.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,467,5,247.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,1035,4,511.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,663,0,14.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,576,3,212.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,946,7,481.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,507,7,760.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,1013,6,107.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (44,130,2,423.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (45,121,7,628.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (45,663,0,748.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (45,467,2,475.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (45,397,6,866.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (46,1113,4,970.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (46,39,1,156.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (46,76,8,541.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (46,968,8,347.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (46,787,0,287.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (47,90,4,752.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (47,102,6,683.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (47,1073,1,767.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (47,809,6,136.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (48,613,6,628.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (48,206,3,881.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (48,50,8,73.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (48,335,6,281.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,1018,2,545.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,422,6,806.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,54,5,95.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,576,8,99.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,870,0,25.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,1126,0,361.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,871,5,892.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,568,0,21.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (49,114,9,648.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,1100,1,208.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,365,5,236.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,955,2,834.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,222,7,352.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,69,8,606.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,454,5,633.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (50,523,5,246.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (51,367,2,916.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (51,1054,1,853.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (51,755,3,985.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (51,306,1,299.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,91,2,945.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,1005,2,685.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,609,8,154.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,458,8,182.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,86,1,203.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,373,2,953.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (52,518,8,191.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (53,584,0,567.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (53,905,1,134.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (53,200,3,853.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (53,284,0,268.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (53,697,1,957.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,915,1,621.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,955,3,388.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,272,5,185.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,283,6,563.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,784,2,211.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,483,0,743.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,363,6,378.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (54,126,2,516.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,1103,5,417.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,988,5,326.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,466,5,743.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,743,4,875.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,883,3,399.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,644,0,720.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,781,0,767.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,795,9,537.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (55,847,2,8.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,974,7,230.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,781,9,942.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,1005,8,771.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,790,7,426.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,644,7,695.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,118,2,744.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,1105,7,885.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,454,1,515.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,424,3,14.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (56,112,3,86.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (57,133,8,811.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (57,711,3,817.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (57,923,4,929.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,111,9,828.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,638,1,943.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,660,1,290.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,562,4,442.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,476,8,472.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,1035,5,627.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (58,228,3,737.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (59,782,4,686.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (59,581,0,462.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (59,503,3,864.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (59,391,8,658.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (59,290,1,220.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (59,0,5,240.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,1037,0,950.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,587,0,968.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,1152,2,177.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,1112,8,814.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,534,3,362.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,392,8,765.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (60,376,1,588.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (61,784,8,476.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (61,43,1,761.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (61,75,4,191.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (61,982,7,122.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (62,396,7,696.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (62,511,9,273.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,173,2,230.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,303,7,837.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,1122,3,677.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,673,7,463.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,65,1,833.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,245,7,670.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,26,9,506.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,425,8,464.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (63,1073,3,836.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (64,321,1,919.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (64,918,7,48.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (64,1156,9,963.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (65,342,2,175.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (65,304,9,971.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (65,610,7,865.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (65,200,9,836.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (65,334,2,385.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,1022,0,668.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,665,7,881.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,719,7,519.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,67,0,252.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,1152,6,515.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,784,7,983.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,357,0,304.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (66,161,1,368.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (67,1099,8,932.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (67,510,4,690.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (67,1079,3,470.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (67,736,3,533.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (68,25,8,361.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (68,320,8,449.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (69,540,2,824.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (69,605,1,752.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (69,450,0,846.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (69,46,0,169.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (69,930,2,412.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (69,260,1,113.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (70,4,6,715.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (70,523,3,641.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (70,638,2,281.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (70,145,9,675.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (70,122,5,30.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (71,1092,2,238.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (71,39,2,245.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (71,335,3,263.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (71,827,2,582.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (72,290,1,957.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (72,664,1,839.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (72,616,0,541.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (72,604,5,537.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (72,736,4,783.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (72,563,4,364.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (73,16,1,76.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (73,187,6,490.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (73,787,1,443.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (73,311,6,80.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (74,118,4,535.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (74,1050,6,219.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (74,146,9,198.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (74,623,2,997.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (74,620,8,245.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (74,287,4,373.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,32,1,321.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,1080,4,410.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,496,5,985.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,152,1,95.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,173,2,281.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,720,7,871.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,673,6,1.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,693,3,292.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (75,967,0,414.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,1099,6,836.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,1155,5,570.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,509,9,393.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,128,5,592.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,1130,0,333.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,452,0,368.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (76,385,4,530.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (77,785,8,147.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (77,643,9,474.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (77,689,1,991.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (77,998,5,583.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (77,692,0,422.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (77,727,6,137.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (78,6,7,335.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (78,628,3,104.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (78,163,9,803.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (79,300,1,994.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (79,736,9,667.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (79,409,4,523.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (80,976,3,387.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (80,303,6,164.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (80,513,5,612.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (80,680,0,572.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (80,947,9,55.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,1069,1,477.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,532,6,652.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,629,5,884.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,254,1,221.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,342,6,833.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,850,2,210.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,1128,2,856.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,86,8,642.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,466,7,810.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (81,1070,5,260.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,292,9,238.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,154,3,635.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,172,5,345.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,843,5,715.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,109,5,405.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,514,4,479.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,812,5,79.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,1002,9,759.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (82,431,1,333.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (83,553,7,878.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (83,742,7,896.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (83,835,2,704.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (83,1121,2,775.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (83,191,6,484.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,961,3,941.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,1155,4,669.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,854,1,172.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,1149,2,875.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,746,7,498.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,712,1,347.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,200,5,157.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,1050,4,460.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,901,0,58.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (84,115,7,185.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,602,5,168.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,1029,1,689.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,804,0,137.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,864,0,352.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,456,1,661.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,260,2,871.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,34,6,631.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,243,5,964.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,97,1,501.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (85,781,7,857.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,55,9,660.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,94,5,31.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,355,2,684.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,186,0,651.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,521,1,973.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,404,9,34.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,156,6,975.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (86,10,8,803.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,1054,8,24.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,301,5,722.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,445,3,938.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,540,3,361.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,912,6,668.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,262,7,376.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,685,8,389.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (87,457,2,659.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,699,2,235.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,95,5,889.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,458,4,76.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,765,4,173.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,667,7,379.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,968,3,570.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (88,1141,4,227.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (89,1051,1,944.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (89,86,8,664.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (89,650,0,104.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (89,627,0,658.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (89,666,7,581.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (89,377,1,851.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,42,5,37.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,178,5,918.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,659,4,453.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,429,7,235.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,418,0,44.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,13,5,178.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,739,0,690.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,418,0,382.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,599,2,941.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (90,381,9,912.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (91,658,5,594.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (91,649,6,122.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (91,587,6,817.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (91,354,3,554.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,667,8,455.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,486,4,549.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,758,6,388.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,1150,3,633.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,434,6,257.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,392,9,855.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,845,2,408.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,560,5,776.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,642,8,806.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (92,7,3,22.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (93,737,5,260.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (93,754,6,988.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (93,1084,8,222.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (93,901,5,163.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (93,946,4,270.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,139,6,371.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,207,2,237.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,1007,7,536.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,683,9,659.3);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,700,4,296.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,30,4,792.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (94,793,3,708.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,555,3,684.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,1064,1,410.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,735,1,364.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,85,1,349.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,485,8,297.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,1152,6,580.0);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,62,1,997.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,280,7,698.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (95,9,9,219.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,1130,1,795.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,215,6,651.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,897,9,213.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,815,5,877.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,1003,6,384.5);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,453,5,338.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (96,518,9,824.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (97,826,0,328.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (97,681,4,462.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (97,990,0,614.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,483,3,144.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,296,6,557.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,358,3,666.7);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,1096,4,199.9);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,1020,2,143.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,495,3,668.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,1016,3,475.8);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,224,8,237.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,482,5,455.4);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (98,212,3,9.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (99,391,5,386.6);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (99,841,6,446.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (99,790,9,270.1);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (99,673,9,243.2);
INSERT INTO tb_ingredient_recipe (id_recipe, id_ingredient, id_unit, quantity) VALUES (99,604,4,960.3);

INSERT INTO tb_tag (name) VALUES ('American');
INSERT INTO tb_tag (name) VALUES ('Apple');
INSERT INTO tb_tag (name) VALUES ('Apples');
INSERT INTO tb_tag (name) VALUES ('Asian');
INSERT INTO tb_tag (name) VALUES ('Asparagus');
INSERT INTO tb_tag (name) VALUES ('Aubergine');
INSERT INTO tb_tag (name) VALUES ('Autumn');
INSERT INTO tb_tag (name) VALUES ('Avocado');
INSERT INTO tb_tag (name) VALUES ('BBQ');
INSERT INTO tb_tag (name) VALUES ('Baking');
INSERT INTO tb_tag (name) VALUES ('Baking with kids');
INSERT INTO tb_tag (name) VALUES ('Barley and quinoa');
INSERT INTO tb_tag (name) VALUES ('Bars and squares');
INSERT INTO tb_tag (name) VALUES ('Beef');
INSERT INTO tb_tag (name) VALUES ('Beetroot');
INSERT INTO tb_tag (name) VALUES ('Best recipes');
INSERT INTO tb_tag (name) VALUES ('Biscuit');
INSERT INTO tb_tag (name) VALUES ('Blackberry');
INSERT INTO tb_tag (name) VALUES ('Blueberry');
INSERT INTO tb_tag (name) VALUES ('Breads');
INSERT INTO tb_tag (name) VALUES ('Breakfast and brunch');
INSERT INTO tb_tag (name) VALUES ('British');
INSERT INTO tb_tag (name) VALUES ('Broccoli');
INSERT INTO tb_tag (name) VALUES ('Brownies');
INSERT INTO tb_tag (name) VALUES ('Cake');
INSERT INTO tb_tag (name) VALUES ('Cakes');
INSERT INTO tb_tag (name) VALUES ('Canapés and party food');
INSERT INTO tb_tag (name) VALUES ('Candies chocolates sweets and snacks');
INSERT INTO tb_tag (name) VALUES ('Chicken');
INSERT INTO tb_tag (name) VALUES ('Chocolate');
INSERT INTO tb_tag (name) VALUES ('Christmas');
INSERT INTO tb_tag (name) VALUES ('Cookies');
INSERT INTO tb_tag (name) VALUES ('Courgette');
INSERT INTO tb_tag (name) VALUES ('Couscous');
INSERT INTO tb_tag (name) VALUES ('Cranberries');
INSERT INTO tb_tag (name) VALUES ('Cream desserts mousses and meringues');
INSERT INTO tb_tag (name) VALUES ('Crepes and pancakes');
INSERT INTO tb_tag (name) VALUES ('Crisps and crumbles');
INSERT INTO tb_tag (name) VALUES ('Cupcakes');
INSERT INTO tb_tag (name) VALUES ('Dips and salty spreads');
INSERT INTO tb_tag (name) VALUES ('Dressings and mayonnaise');
INSERT INTO tb_tag (name) VALUES ('Drinks');
INSERT INTO tb_tag (name) VALUES ('Drinks and cocktails');
INSERT INTO tb_tag (name) VALUES ('Duck');
INSERT INTO tb_tag (name) VALUES ('Egg');
INSERT INTO tb_tag (name) VALUES ('Eggs');
INSERT INTO tb_tag (name) VALUES ('Fennel');
INSERT INTO tb_tag (name) VALUES ('Fish');
INSERT INTO tb_tag (name) VALUES ('Fish and seafood');
INSERT INTO tb_tag (name) VALUES ('Fish and shellfish');
INSERT INTO tb_tag (name) VALUES ('Fondue');
INSERT INTO tb_tag (name) VALUES ('French');
INSERT INTO tb_tag (name) VALUES ('Frozen desserts');
INSERT INTO tb_tag (name) VALUES ('Fruit');
INSERT INTO tb_tag (name) VALUES ('Game');
INSERT INTO tb_tag (name) VALUES ('Gluten-free');
INSERT INTO tb_tag (name) VALUES ('Goose guinea fowl and other poultry');
INSERT INTO tb_tag (name) VALUES ('Greek');
INSERT INTO tb_tag (name) VALUES ('Grilled');
INSERT INTO tb_tag (name) VALUES ('Grilling marinades');
INSERT INTO tb_tag (name) VALUES ('Healthy');
INSERT INTO tb_tag (name) VALUES ('Healthy eating');
INSERT INTO tb_tag (name) VALUES ('Hors d oeuvres');
INSERT INTO tb_tag (name) VALUES ('Ice cream and sorbet');
INSERT INTO tb_tag (name) VALUES ('Indian');
INSERT INTO tb_tag (name) VALUES ('Italian');
INSERT INTO tb_tag (name) VALUES ('Jam and sweet spreads');
INSERT INTO tb_tag (name) VALUES ('Japanese');
INSERT INTO tb_tag (name) VALUES ('Jar mixes and ketchups');
INSERT INTO tb_tag (name) VALUES ('Kale');
INSERT INTO tb_tag (name) VALUES ('Lamb');
INSERT INTO tb_tag (name) VALUES ('Leftovers');
INSERT INTO tb_tag (name) VALUES ('Legumes');
INSERT INTO tb_tag (name) VALUES ('Lunch ideas');
INSERT INTO tb_tag (name) VALUES ('Main courses');
INSERT INTO tb_tag (name) VALUES ('Meal salads');
INSERT INTO tb_tag (name) VALUES ('Mediterranean');
INSERT INTO tb_tag (name) VALUES ('Mexican');
INSERT INTO tb_tag (name) VALUES ('Middle Eastern');
INSERT INTO tb_tag (name) VALUES ('Muffins and dessert breads');
INSERT INTO tb_tag (name) VALUES ('Mushroom');
INSERT INTO tb_tag (name) VALUES ('Non alcoholic drinks mocktails');
INSERT INTO tb_tag (name) VALUES ('Pancake');
INSERT INTO tb_tag (name) VALUES ('Pasta');
INSERT INTO tb_tag (name) VALUES ('Pastries');
INSERT INTO tb_tag (name) VALUES ('Pies');
INSERT INTO tb_tag (name) VALUES ('Pizza');
INSERT INTO tb_tag (name) VALUES ('Pork');
INSERT INTO tb_tag (name) VALUES ('Potato');
INSERT INTO tb_tag (name) VALUES ('Preserves and sauces');
INSERT INTO tb_tag (name) VALUES ('Pudding and tapioca');
INSERT INTO tb_tag (name) VALUES ('Pumpkin');
INSERT INTO tb_tag (name) VALUES ('Quiches and savoury pies');
INSERT INTO tb_tag (name) VALUES ('Quick');
INSERT INTO tb_tag (name) VALUES ('Quick and easy');
INSERT INTO tb_tag (name) VALUES ('Quinoa');
INSERT INTO tb_tag (name) VALUES ('Raspberry');
INSERT INTO tb_tag (name) VALUES ('Recipes for one');
INSERT INTO tb_tag (name) VALUES ('Recipes for two');
INSERT INTO tb_tag (name) VALUES ('Rhubarb');
INSERT INTO tb_tag (name) VALUES ('Rice');
INSERT INTO tb_tag (name) VALUES ('Risotto');
INSERT INTO tb_tag (name) VALUES ('Salmon');
INSERT INTO tb_tag (name) VALUES ('Sandwiches');
INSERT INTO tb_tag (name) VALUES ('Sauces and condiments');
INSERT INTO tb_tag (name) VALUES ('Sauces butters and pestos');
INSERT INTO tb_tag (name) VALUES ('Savoury breads');
INSERT INTO tb_tag (name) VALUES ('Scandinavian');
INSERT INTO tb_tag (name) VALUES ('Scone');
INSERT INTO tb_tag (name) VALUES ('Seafood');
INSERT INTO tb_tag (name) VALUES ('Sides');
INSERT INTO tb_tag (name) VALUES ('Slow cooker');
INSERT INTO tb_tag (name) VALUES ('Snacks and light meals');
INSERT INTO tb_tag (name) VALUES ('Spanish');
INSERT INTO tb_tag (name) VALUES ('Spring');
INSERT INTO tb_tag (name) VALUES ('Starters');
INSERT INTO tb_tag (name) VALUES ('Strawberry');
INSERT INTO tb_tag (name) VALUES ('Summer');
INSERT INTO tb_tag (name) VALUES ('Sweet potato');
INSERT INTO tb_tag (name) VALUES ('Tart');
INSERT INTO tb_tag (name) VALUES ('Tofu');
INSERT INTO tb_tag (name) VALUES ('Tofu soy and co');
INSERT INTO tb_tag (name) VALUES ('Tomato');
INSERT INTO tb_tag (name) VALUES ('Tomatoes');
INSERT INTO tb_tag (name) VALUES ('Tuna');
INSERT INTO tb_tag (name) VALUES ('Turkey');
INSERT INTO tb_tag (name) VALUES ('Uncategorized');
INSERT INTO tb_tag (name) VALUES ('Veal');
INSERT INTO tb_tag (name) VALUES ('Vegan');
INSERT INTO tb_tag (name) VALUES ('Vegetables');
INSERT INTO tb_tag (name) VALUES ('Vegetables and gratinees');
INSERT INTO tb_tag (name) VALUES ('Vegetarian');
INSERT INTO tb_tag (name) VALUES ('Winter');
INSERT INTO tb_tag (name) VALUES ('Yogurt and cheese');

INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (1,67);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (16,87);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (5,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (5,53);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (62,79);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (58,67);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (52,14);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (87,48);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (93,41);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (52,86);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (6,39);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (73,52);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (21,32);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (55,60);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (26,82);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (90,14);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (6,58);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (120,59);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (99,72);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (53,78);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (18,15);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (26,35);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (42,83);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (88,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (106,23);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (105,20);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (60,95);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (44,33);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (120,83);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (85,56);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (117,39);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (81,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (24,28);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (131,25);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (25,19);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (14,17);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (52,26);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (52,24);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (97,77);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (57,70);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (33,45);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (74,50);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (3,18);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (71,71);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (53,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (130,10);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (132,44);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (45,54);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (40,5);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (21,8);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,8);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (20,30);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (61,37);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (55,45);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,87);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (37,47);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (19,33);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (50,71);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (53,65);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (103,21);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (123,48);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (54,20);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (19,74);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (120,68);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (46,85);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (130,71);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (117,93);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (14,84);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (110,47);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (102,54);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (132,75);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (74,22);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (69,31);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (100,84);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (124,86);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (40,56);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (124,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (102,31);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (96,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (41,81);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (81,63);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (116,99);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (15,71);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (24,46);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (58,40);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (114,11);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (27,73);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (70,20);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (85,48);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (119,73);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (17,94);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (79,13);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (80,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (73,71);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (79,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (2,11);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (4,43);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (120,96);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (27,24);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (127,70);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (71,57);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (19,82);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (94,83);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (65,54);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (65,25);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (101,8);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (62,22);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (65,54);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (94,60);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (100,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (121,40);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (76,98);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (129,4);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,63);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (123,41);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (20,13);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (84,37);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (79,46);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (126,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (8,19);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (107,83);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (96,55);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (115,61);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (90,69);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (103,95);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (87,3);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (51,95);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (44,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (20,62);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (3,69);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (86,15);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (47,33);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (22,78);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (31,79);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (39,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (88,45);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (125,7);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (21,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (124,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (5,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (89,37);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (51,83);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (104,86);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (132,5);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (108,85);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (132,14);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (120,21);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (53,76);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (68,78);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (110,53);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (105,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (25,67);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (33,56);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (22,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (14,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (7,88);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (114,91);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (103,57);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (121,92);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (120,5);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (38,39);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (70,71);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (24,27);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (1,12);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (65,58);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,72);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (22,44);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (8,46);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (99,16);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (130,12);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (127,38);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (38,10);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (7,76);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (93,60);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (95,26);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (124,9);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (68,5);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,35);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (59,14);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (104,79);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (102,43);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (108,20);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (5,22);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (2,7);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (113,38);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (58,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (101,28);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (118,37);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (13,62);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (64,57);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (22,52);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (70,74);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (35,93);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (36,57);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (82,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (18,1);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (59,20);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (5,62);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (60,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (51,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (125,11);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (93,31);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (86,91);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (42,74);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (33,26);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (40,94);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (90,90);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (99,52);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (89,90);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (40,89);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (127,93);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (47,65);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (33,89);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (90,25);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (2,32);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (21,63);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (32,68);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (37,94);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (1,49);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (39,92);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (132,89);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (64,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (85,6);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (16,96);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (0,64);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (46,53);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (121,7);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (26,6);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (78,64);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (26,48);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (2,29);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (88,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (31,38);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (57,2);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (112,86);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (123,27);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (62,19);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (74,59);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (107,45);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (38,4);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (55,21);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (17,57);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (128,66);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (24,92);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (85,33);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (104,50);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (83,27);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (51,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (6,98);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (18,28);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (96,79);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,6);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (74,16);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (89,36);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (17,22);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (6,22);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (15,73);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (98,47);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (27,13);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (14,36);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (93,99);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (32,33);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (105,20);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (67,32);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (38,55);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (0,15);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (21,60);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (46,12);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (51,15);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (63,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (45,86);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (93,12);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (88,12);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (39,31);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (14,8);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (65,69);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (53,40);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (21,51);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (39,95);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (73,64);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (130,44);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (85,6);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (129,80);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (20,35);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (24,54);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (49,87);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (103,58);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (116,30);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (6,42);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (104,35);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (66,45);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (103,11);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (92,44);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (133,32);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (37,94);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (48,40);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (30,34);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (20,12);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (57,26);
INSERT INTO tb_tag_recipe (id_tag, id_recipe) VALUES (16,2);

INSERT INTO tb_favourite (id_recipe, id_member) VALUES (49, 4);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (63, 111);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (70, 48);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (58, 109);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (64, 39);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (13, 116);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (20, 338);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (71, 25);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (48, 115);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (52, 332);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (12, 222);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (74, 58);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (38, 162);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (49, 240);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (18, 217);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (16, 158);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (59, 237);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (44, 95);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (73, 235);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (18, 24);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (28, 230);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (29, 126);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (41, 42);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (79, 141);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (10, 12);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (73, 131);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (61, 84);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (8, 217);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (28, 113);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (71, 303);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (44, 192);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (50, 230);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (32, 323);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (33, 19);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (43, 87);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (75, 300);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (30, 122);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (52, 194);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (71, 65);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (72, 86);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (17, 18);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (27, 90);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (18, 5);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (75, 8);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (99, 325);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (93, 317);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (95, 168);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (55, 249);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (2, 329);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (70, 317);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (93, 128);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (35, 305);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (40, 50);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (69, 89);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (40, 174);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (84, 221);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (90, 50);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (99, 313);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (43, 118);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (84, 8);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (30, 257);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (94, 120);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (62, 220);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (70, 156);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (40, 290);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (89, 167);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (62, 41);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (32, 136);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (62, 293);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (3, 69);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (43, 111);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (86, 271);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (77, 62);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (8, 244);
INSERT INTO tb_favourite (id_recipe, id_member) VALUES (12, 245);

